import { useState, useEffect } from 'react'
import { Connection, PublicKey, LAMPORTS_PER_SOL, Transaction, SystemProgram } from '@solana/web3.js'
import { XRWorld } from './XRWorld'
import './App.css'
import './xr.css'

// Constants
const SOLANA_NETWORK = 'devnet'
const CONNECTION = new Connection(`https://api.${SOLANA_NETWORK}.solana.com`, 'confirmed')

function App() {
  const [connected, setConnected] = useState(false)
  const [walletAddress, setWalletAddress] = useState<string | null>(null)
  const [balance, setBalance] = useState<number | null>(null)
  const [recipient, setRecipient] = useState('')
  const [amount, setAmount] = useState('')
  const [txSig, setTxSig] = useState<string | null>(null)
  const [vibePrompt, setVibePrompt] = useState('')
  const [generatedCode, setGeneratedCode] = useState<string | null>(null)
  const [appView, setAppView] = useState<'pulse' | 'vibe' | 'xr'>('pulse')

  // Wallet detection
  useEffect(() => {
    const checkWallet = async () => {
      if ('solana' in window) {
        const solana = (window as any).solana
        if (solana?.isPhantom) {
          try {
            const response = await solana.connect({ onlyIfTrusted: true })
            const pubKey = response.publicKey.toString()
            setWalletAddress(pubKey)
            setConnected(true)
            await fetchBalance(pubKey)
          } catch (e) {
            console.log('No trusted connection found')
          }
        }
      }
    }
    checkWallet()
  }, [])

  const fetchBalance = async (address: string) => {
    try {
      const pubKey = new PublicKey(address)
      const bal = await CONNECTION.getBalance(pubKey)
      setBalance(bal / LAMPORTS_PER_SOL)
    } catch (e) {
      console.error('Balance fetch error:', e)
    }
  }

  const connectWallet = async () => {
    if ('solana' in window) {
      const solana = (window as any).solana
      if (solana?.isPhantom) {
        try {
          const response = await solana.connect()
          const pubKey = response.publicKey.toString()
          setWalletAddress(pubKey)
          setConnected(true)
          await fetchBalance(pubKey)
        } catch (e) {
          console.error('Connection error:', e)
        }
      } else {
        alert('Phantom wallet not found! Install it from phantom.app')
      }
    } else {
      alert('Solana wallet not found! Install the Phantom extension.')
    }
  }

  const disconnectWallet = () => {
    if ('solana' in window) {
      const solana = (window as any).solana
      solana.disconnect()
    }
    setConnected(false)
    setWalletAddress(null)
    setBalance(null)
  }

  const sendSol = async () => {
    if (!connected || !walletAddress) return
    if (!recipient || !amount) {
      alert('Enter recipient address and amount')
      return
    }

    try {
      const fromPubKey = new PublicKey(walletAddress)
      const toPubKey = new PublicKey(recipient)
      const lamports = parseFloat(amount) * LAMPORTS_PER_SOL

      const transaction = new Transaction().add(
        SystemProgram.transfer({
          fromPubkey: fromPubKey,
          toPubkey: toPubKey,
          lamports,
        })
      )

      const solana = (window as any).solana
      const { blockhash } = await CONNECTION.getLatestBlockhash()
      transaction.recentBlockhash = blockhash
      transaction.feePayer = fromPubKey

      const signed = await solana.signAndSendTransaction(transaction)
      setTxSig(signed)
      alert(`Sent ${amount} SOL! TX: ${signed}`)
      await fetchBalance(walletAddress)
      setRecipient('')
      setAmount('')
    } catch (e) {
      console.error('Send error:', e)
      alert('Transaction failed! Check address and try again.')
    }
  }

  const vibeCode = async () => {
    if (!vibePrompt.trim()) return

    // Simulated AI code generation
    const mockCode = `
// PULSE App — Generated from: "${vibePrompt}"

import { useState } from 'react'
import { Connection, PublicKey } from '@solana/web3.js'

export default function GeneratedApp() {
  const [state, setState] = useState({})

  // Your vibe-coded features here:
  // ${vibePrompt}

  return (
    <div className="pulse-generated">
      <h1>${vibePrompt}</h1>
      <p>Generated by PULSE Vibe Engine ✨</p>
    </div>
  )
}
`

    setGeneratedCode(mockCode)
  }

  return (
    <div className="app">
      {/* Header */}
      <header className="header">
        <div className="logo">PULSE ⚡</div>
        <nav className="nav">
          <button
            className={appView === 'pulse' ? 'active' : ''}
            onClick={() => setAppView('pulse')}
          >
            💰 Pulse
          </button>
          <button
            className={appView === 'vibe' ? 'active' : ''}
            onClick={() => setAppView('vibe')}
          >
            ✨ Vibe Code
          </button>
          <button
            className={appView === 'xr' ? 'active' : ''}
            onClick={() => setAppView('xr')}
          >
            🥽 XR
          </button>
        </nav>
      </header>

      {/* Main Content */}
      <main className="main">
        {appView === 'pulse' ? (
          <div className="pulse-view">
            <h1>Solana SuperApp</h1>
            <p className="tagline">Build fast. Pay instant. Vibes only.</p>

            {!connected ? (
              <div className="connect-section">
                <button className="connect-btn" onClick={connectWallet}>
                  <span className="wallet-icon">👻</span>
                  Connect Phantom Wallet
                </button>
                <p className="hint">Install Phantom from phantom.app if you don't have it</p>
              </div>
            ) : (
              <div className="wallet-connected">
                <div className="wallet-card">
                  <div className="wallet-icon-lg">👻</div>
                  <div className="wallet-info">
                    <p className="wallet-label">Connected Wallet</p>
                    <p className="wallet-address">
                      {walletAddress?.slice(0, 4)}...{walletAddress?.slice(-4)}
                    </p>
                    <p className="wallet-balance">{balance?.toFixed(4)} SOL</p>
                  </div>
                  <button className="disconnect-btn" onClick={disconnectWallet}>
                    Disconnect
                  </button>
                </div>

                <div className="send-form">
                  <h2>Send SOL</h2>
                  <input
                    type="text"
                    placeholder="Recipient wallet address"
                    value={recipient}
                    onChange={(e) => setRecipient(e.target.value)}
                    className="input"
                  />
                  <input
                    type="number"
                    placeholder="Amount in SOL"
                    value={amount}
                    onChange={(e) => setAmount(e.target.value)}
                    className="input"
                    step="0.01"
                    min="0"
                  />
                  <button className="send-btn" onClick={sendSol}>
                    Send ⚡
                  </button>
                  {txSig && (
                    <p className="tx-success">
                      Transaction sent! Signature: {txSig.slice(0, 20)}...
                    </p>
                  )}
                </div>
              </div>
            )}
          </div>
        ) : (
          <div className="vibe-view">
            <h1>Vibe Code ✨</h1>
            <p className="tagline">Describe your app. Watch it appear.</p>

            <div className="vibe-interface">
              <textarea
                className="vibe-input"
                placeholder="Describe your app... e.g., 'A DeFi app with token swaps and a social feed'"
                value={vibePrompt}
                onChange={(e) => setVibePrompt(e.target.value)}
                rows={4}
              />
              <button className="vibe-btn" onClick={vibeCode}>
                Generate App ✨
              </button>

              {generatedCode && (
                <div className="code-output">
                  <pre>{generatedCode}</pre>
                  <button
                    className="copy-btn"
                    onClick={() => navigator.clipboard.writeText(generatedCode)}
                  >
                    📋 Copy Code
                  </button>
                </div>
              )}
            </div>
          </div>
        )}
        {appView === 'xr' && (
          <div className="xr-view">
            <h1>🥽 XR World</h1>
            <p className="tagline">AR • VR • XR — Your imagination is the limit</p>
            <XRWorld />
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="footer">
        <p>PULSE — Vibe-coded on Solana | Powered by AI ⚡</p>
        <p className="hackathon">NOAH.AI Solana Hackathon 2026</p>
      </footer>
    </div>
  )
}

export default App
